@App_HostAddress = http://localhost:5125
@GithubAppToken = xxxxx

GET {{App_HostAddress}}/jwt
Accept: text/plain

###
GET {{App_HostAddress}}/installations
Accept: application/json

###
GET {{App_HostAddress}}/installations/giulianil-sso/token
Accept: text/plain

###
GET {{App_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET https://api.github.com/app/installations
Authorization: Bearer {{GithubAppToken}}
Accept: application/vnd.github+json
User-Agent: myapp